#!/bin/bash

# Author: Tercio Gaudencio Filho <terciofilho [at] gmail.com>

readonly DEFAULT=/etc/default/firewall
readonly LSB_FUNCTIONS="/lib/lsb/init-functions"

# The following variables may be overwritten in /etc/default/firewall
RULESET_FOLDER="/etc/firewall"
MAIN_RULESET="${RULESET_FOLDER}/main.ruleset"
SYSCTL_FILE="${RULESET_FOLDER}/sysctl.conf"
# End of overwritable variables

# Overwrite default variables
[[ -r "${DEFAULT}" ]] && . "${DEFAULT}"

check_dep() {
  if ! $(command -v "${1}" > /dev/null); then
    log_failure_msg "${1} program not available!" >&2
    exit 1
  fi
}

enable() {
  ! check && return $?

  log_begin_msg "Applying sysctl variables"
  OUTPUT=$(sysctl -p ${SYSCTL_FILE} 2>&1)
  RETVAL=$?
  ! log_end_msg $RETVAL && echo "$OUTPUT" >&2
  if [[ $RETVAL -eq 0 ]]; then
    log_begin_msg "Applying nftables ruleset"
    # NOTE: Running nft with -f option the ruleset folder must be the cwd.
    OUTPUT=$(cd "${RULESET_FOLDER}"; nft -f ${MAIN_RULESET})
    RETVAL=$?
    ! log_end_msg $RETVAL && echo "$OUTPUT" >&2
    return $RETVAL
  fi
}

disable() {
  log_begin_msg "Flushing nftables ruleset"
  nft flush ruleset
  log_end_msg $?

  log_begin_msg "Restoring sysctl default variables"
  sysctl -p > /dev/null
  log_end_msg $?
}

# Status of the nft ruleset
status() {
  OUTPUT=$(nft list ruleset)
  if [[ -n "$OUTPUT" ]]; then
    log_action_msg "Firewall running"
    return 0
  fi
  log_action_msg "Firewall not running"
  return 1
}

check() {
  log_begin_msg "Checking Ruleset"
  OUTPUT=$(cd "${RULESET_FOLDER}"; nft -c -f ${MAIN_RULESET} 2>&1)
  RETVAL=$?
  ! log_end_msg $RETVAL && echo "$OUTPUT" >&2
  return $RETVAL
}

# Install firewall link on /usr/sbin
install() {
  log_begin_msg "Creating /usr/sbin link"
  [[ ! -f /usr/sbin/firewall ]] && ln -s $(readlink -f "${0}") /usr/sbin/firewall
  log_end_msg $?
}

logging() {
  if [[ ! -f "${RULESET_FOLDER}/log-${1}.ruleset" ]]; then
    log_failure_msg "Invalid logging option"
    return $?
  fi

  [[ -h "${RULESET_FOLDER}/log.ruleset" ]] && rm "${RULESET_FOLDER}/log.ruleset"
  [[ $? -eq 0 ]] && ln -s "${RULESET_FOLDER}/log-${1}.ruleset" "${RULESET_FOLDER}/log.ruleset"

  log_success_msg "Configuring logging"
}

# Create a logging options based on the log-*.ruleset files in the $RULESET_FOLDER
get_logging_opts() {
      logging_opts=""
      for log_file in $(find ${RULESET_FOLDER} -iname 'log-*.ruleset' -type f -printf "%f\n"); do
        opt=${log_file/log-/}
        opt=${opt/.ruleset/}
        logging_opts="${logging_opts}|${opt}"
      done
      logging_opts=${logging_opts:1}
}

# Main function
main() {
  # Check dependencies
  check_dep "nft"
  check_dep "sysctl"
  check_dep "find"

  case "$1" in
    enable|disable|status|check|install|logging)
      $1 ${@:2}
      exit $?
    ;;

    *)
      get_logging_opts
      echo "Usage: ${0} {install|check|enable|disable|logging {${logging_opts}}}"
      exit 255
    ;;
  esac
}

# The LSB functions must be present, then source it.
if [[ ! -r "$LSB_FUNCTIONS" ]]; then
  echo "LSB functions not found/could not read: script cannot run" >&2
  exit 1
fi
. "${LSB_FUNCTIONS}"

# Run
main "$@"
